### ISSUE TITLE
You might be interested in my Python library for Arlo cameras.

### ISSUE THREAD

**Issue by jeffreydwalter** [LenShustek/ArloCamera#1]
Hey, cool thing you did here! I just wrote this little Python library for interacting with Arlo cameras that you may or may not find useful. Enjoy!

https://github.com/jeffreydwalter/arlo

**Comment by LenShustek** [comment]
Nice job of reverse-engineering the Arlo protocol! That's a much more robust approach than what I did, which has already broken because they've changed their UI screens.

If I have a chance to go back to it, I might try replacing the code in my Raspberry Pi box to change modes following your example, rather than by "magic fingers".

**Comment by LenShustek** [comment]
Did you try setting arm/disarm modes? I can't get that to work, although I can successfully log on, list devices, etc.  I'm trying to disarm by sending to  https://arlo.netgear.com/hmsweb/users/devices/notify/yyyyyyyyyyyyy  
a request body that looks like this:
{'action': 'set',
 'from': 'xxx-xxxxxxx_web',
 'properties': {'active': 'mode0'},
 'publishResponse': True,
 'resource': 'modes',
 'to': 'yyyyyyyyyyyyy',
 'transId': ''}
with the login authorization in the request header. That's pretty much what I see the browser doing, but I get "400 Client Error: Bad Request". I've tried all sorts of variations with no joy.

**Comment by jeffreydwalter** [comment]
Hey Len,

You have to send the XCloudId header with the /notify requests. Are you
using my python module? If not, I highly recommend it. It is braindead
simple to use. :)

Have you tried using my Arm()/Disarm() methods in the Arlo module? I JUST
tested these methods and they work okay for me.

Check out the example here: https://github.com/jeffreydwalter/arlo/blob/master/README.md

Cheers,
Jeff

**Comment by LenShustek** [comment]
Aha! I had grabbed a copy of your module when you first told me about it 10 days ago, before you had added the arm/disarm code. With the addition of XCloudId mine works now too. Many thanks! I'll be changing my little Raspberry Pi box to do that.

**Comment by LenShustek** [comment]
Jeff,

I changed my box to use your library. It works great, and is much more robust. Thanks!

I assume it's coincidental that I can't get to the "live view" on my cameras? It says "Please wait" forever. But everything else, including motion alarms when the cameras are armed, seems to work. Weird.

-- Len

**Comment by jeffreydwalter** [comment]
Hey Len,

I just merged your commit, thanks for contributing!

I'm glad the library is working out for you!

Are you saying your cameras aren't streaming the live view from the Arlo
app and/or website?

If yes, I just tried my live view and it worked as expected. Maybe whatever
you're doing in your program put the camera/base station in a funky state.

If you're talking about streaming via the API, it's possible there's a bug
in that method.

Let me know and I'll do what I can to help figure it out!

Jeff

On Sep 17, 2016 7:59 PM, "Len Shustek" notifications@github.com wrote:

Jeff,

I changed my box to use your library. It works great, and is much more
robust. Thanks!

I assume it's coincidental that I can't get to the "live view" on my
cameras? It says "Please wait" forever. But everything else, including
motion alarms when the cameras are armed, seems to work. Weird.

-- Len

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/LenShustek/ArloCamera/issues/1#issuecomment-247817236,
or mute the thread

**Comment by LenShustek** [comment]
It looks like a browser problem: I can't stream from either of my base stations through Chrome on my main PC. But it works from IE, and it works from Chrome on another computer! I tried deleting all cookies with "arlo" or "netgear" in them, but it didn't help.  I may have confused it somehow because I access two different base stations using two different email addresses.

In any case it doesn't look like it has anything to do with your library. The only methods I use are Login, Arm/Disarm, and Logout.

**Comment by LenShustek** [comment]
I found the problem, and it was my fault.  In a paranoid moment I had set my Chrome settings for content/plugins to "Let me choose when to run plugin content". If you do that, streaming from Arlo cameras won't work, and you are never given any notification or choice; it just hangs saying "Please wait" . Changing to "Detect and run important plugin content (recommended)" lets it work. 

Sorry for the false alarm. My two Arlo camera switchboxes are working great, thanks to your library.

**Comment by jeffreydwalter** [comment]
Hey Len,

I'm glad you found the issue! Extra glad to hear it wasn't my code. ;)

Thanks for the kind shout outs in your library.

Cheers,
Jeff
